#!/bin/bash
exec 2>/dev/null
#debug=1
#set -x
conf=$HOME/.bcastrc

#create configfile if not existing
if [ ! -f $conf ];then
	echo "# config settings ">$conf
	echo "downloadDir=$HOME/bashcast">>$conf
	echo "playlist=$HOME/bcaster.m3u">>$conf
	echo "id3tags=true">>$conf
	echo "id3Jpg=true">>$conf
        echo "cleanOld=true">>$conf
	echo >>$conf
	echo "# podcast urls">>$conf
	echo >>$conf
	echo
	echo "created config file $conf, edit according to your needs"
	echo
	exit 1
fi

# read config params
config=`cat $conf |egrep -v "http|#|^$|^ "`  
for c in $config ;do
	echo $c|grep "downloadDir=">/dev/null && downloadDir=`echo $c|sed -e 's/downloadDir=//'`>/dev/null
	echo $c|grep "cleanOld=true">/dev/null && cleanOld=`echo $c|sed -e 's/cleanOld=//'`
	echo $c|grep "playlist=">/dev/null && playlist=`echo $c|sed -e 's/playlist=//'`
	echo $c|grep "id3tags=true">/dev/null && id3tags=`echo $c|sed -e 's/id3tags=//'`
	echo $c|grep "id3Jpg=true">/dev/null && id3Jpg=`echo $c|sed -e 's/id3Jpg=//'`
done

# check config params
if [ ! -d $downloadDir ];then
	mkdir -p $downloadDir 
	if [ $? -eq 1 ];then
		echo "### Invalid downloadDir, check config"
		err=1
	fi
fi

if [ ! -f $playlist ]; then
	echo "# bcaster playlist" > $playlist
	if [ $? -eq 1 ];then
		echo "### Invalid playlist config, skipping creation"
	fi
fi


# read rss urls
urls=`cat $conf| egrep "^http"`
[ -d "$2" ] && downloadDir=$2 && playlist="/tmp/pl.m3u"

# check for params
echo $1 |grep http
[ $? -eq 0 ] && urls=`echo $1` 

id=-1
for rss in $urls; do
	#echo
	id=$((id+1))
	wget -O - $rss >/tmp/bc.tmp 
	podCastTitle=`cat /tmp/bc.tmp|grep -o 'title>[^<]*'|grep -o '[^>]*$'|head -1|sed -e 's/\&amp;/\&/g'`
	if [ -z "$podCastTitle" ];then
		echo "### Error downloading $rss"
		continue
	fi
	echo "Podcast: $podCastTitle"

	# check newest bottom or top
	top=`cat /tmp/bc.tmp | grep -o '<pubDate>[^/]*'|grep -o '[0-9][0-9][0-9][0-9]'|head -1`
	bot=`tac /tmp/bc.tmp | grep -o '<pubDate>[^/]*'|grep -o '[0-9][0-9][0-9][0-9]'|head -1`
	if [ $bot -eq $top ];then
		mon=`cat /tmp/bc.tmp | grep -o '<pubDate>[^/]*'|grep -o '[ ][A-Z][a-z][a-z]'|head -1|sed -e 's/ //'`
		top=`date --date="$(printf "01 %s" $mon)" +"%m"`
		mon=`tac /tmp/bc.tmp | grep -o '<pubDate>[^/]*'|grep -o '[ ][A-Z][a-z][a-z]'|head -1|sed -e 's/ //'`
		bot=`date --date="$(printf "01 %s" $mon)" +"%m"`
	fi
	if [ $bot -eq $top ];then
		top=`cat /tmp/bc.tmp | grep -o '<pubDate>[^/]*'|grep -o "[ ][0-9][0-9][ ]"|head -1|tr -d " "`
		bot=`tac /tmp/bc.tmp | grep -o '<pubDate>[^/]*'|grep -o "[ ][0-9][0-9][ ]"|head -1|tr -d " "`
	fi
	if [ $top -ge $bot ];then
		item=`cat /tmp/bc.tmp|grep -n "<item>" |head -1|awk -F':' '{print $1}'`
		title=`sed -n $item,500p /tmp/bc.tmp | grep -o "<title>[^<]*"|grep -o "[^>]*$"|head -1|sed -e 's/\&amp;/\&/g'`
		[[ "$title" == [A-Za-z0-9]* ]] || title=`sed -n $item,100p /tmp/bc.tmp | grep -o "title>[^]]*"|grep -o "[^[]*$"|head -1|sed -e 's/\&amp;/\&/g'`
		file=`cat /tmp/bc.tmp|grep -i "<enclosure"|grep -o 'url=.*'|awk -F'"' '{print $2}'|head -1`
		link=`cat /tmp/bc.tmp|grep -o "link>[^]]*"|grep -o "http[^[]*mp3"|head -1`
	else
		title=`tac /tmp/bc.tmp | grep -o "<title>[^<]*"|grep -o "[^>]*$"|head -1|sed -e 's/\&amp;/\&/g'`
		[[ "$title" == [A-Za-z0-9]* ]] || title=`tac /tmp/bc.tmp | grep -o "title>[^]]*"|grep -o "[^[]*$"|head -1|sed -e 's/\&amp;/\&/g'`
		file=`tac /tmp/bc.tmp|grep -i "<enclosure"|grep -o 'url=.*'|awk -F'"' '{print $2}'|head -1`
		link=`cat /tmp/bc.tmp|grep -o "link>[^]]*"|grep -o "http[^[]*mp3"|head -1`
	fi
	echo $link|grep "\.mp3" && file=$link
	filename=$downloadDir"/"$id"_"`echo $file|grep -o '[^/]*$'|awk -F'?' '{print $1}'`
	echo $filename | egrep ".bin$"
	[ $? -eq 0 ] && filename=$filename".mp3"
	if [ ! -f $filename ] ;then
		echo "Downloading $filename ..."
		wget -O $filename $file
		if [ $? -eq 1 ];then
			echo "### Error downloading $file"
			continue
		else
			[[ "$filename" == *mp3* ]] && isMp3=1
			if [ ! -z "id3tag" ] && [ ! -z "$isMp3" ];then
				echo "Add id3Tag..."
				id3tag -a "$podCastTitle"  -s "$title" $filename|grep "++"
			fi
			#eyeD3 $filename |grep image>/dev/null
			if [ ! -z "$id3Jpg" ]&& [ ! -z "$isMp3" ];then
				echo "Add id3 Image..."
				img=`cat /tmp/bc.tmp |egrep "\.jpg|\.png|\.gif"|grep -o 'http[^<]*'|sed -e 's/".*//'|head -1`
				echo $img|egrep "\.jpg$|\.png$|\.gif$"
				[ $? -eq 1 ] && img=`cat /tmp/bc.tmp |egrep "\.jpg|\.png|\.gif"|grep -o 'http[^<]*'|sed -e 's/".*//'|egrep "\.jpg|\.png|\.gif"|head -1`
				echo $img
				wget -O /tmp/bc.jpg $img >/dev/null
				if [ $? -eq 1 ];then
					echo "### Error downloading Image"
				else
					eyeD3 --remove-all-images $filename
					eyeD3 --add-image="/tmp/bc.jpg":OTHER $filename |grep "OTHER"
				fi
			fi
			if [ ! -z "$cleanOld" ];then
				echo "delete old podcasts"
				cd $downloadDir
				ls -t "$id"_*|grep -v `ls -t "$id"_*|head -1`|xargs rm
			fi
		fi
	else
		if [ ! -z "$cleanOld" ];then
			#echo "delete old podcasts"
			cd $downloadDir
			ls -t "$id"_*|grep -v `ls -t "$id"_*|head -1`|xargs rm
		fi
		continue
	fi
done

# create playlist
if [ -f $playlist ]; then
	cd $downloadDir
	files=`ls -t *.???|grep -v m3u`
	cat /dev/null > $playlist
	for f in $files;do
		echo $downloadDir/$f >>$playlist
	done
	echo "created playlist: $playlist"
fi

# refreh kodi db
curl -s --data-binary '{"jsonrpc": "2.0", "method": "AudioLibrary.clean", "id": "mybash"}' -H "content-type:application/json" -H 'content-type: application/json;' http://192.168.1.24:8080/jsonrpc
echo
curl -s --data-binary '{"jsonrpc": "2.0", "method": "AudioLibrary.Scan", "id": "mybash"}' -H "content-type:application/json" -H 'content-type: application/json;' http://192.168.1.24:8080/jsonrpc
echo
